export const GET_DISHES_SUCCES = "GET_DISHES_SUCCES";
export const GET_DISHES_FAILURE = "GET_DISHES_FAILURE";
export const GET_DISHES_STARTED = "GET_DISHES_STARTED";

export const GET_DISH_NEW = "GET_DISH_NEW";

export const GET_DISH_BY_ID_STARTED = "GET_DISH_BY_ID_STARTED";
export const GET_DISH_BY_ID_SUCCES = "GET_DISH_BY_ID_SUCCES";
export const GET_DISH_BY_ID_FAILURE = "GET_DISH_BY_ID_FAILURE";
