export const GET_INGREDIENTS_STARTED = "GET_INGREDIENTS_STARTED";
export const GET_INGREDIENTS_SUCCES = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILURE = "GET_INGREDIENTS_FAILURE";
export const POST_IN_CURRENT_INGREDIENTS = "POST_IN_CURRENT_INGREDIENTS";
export const DELETE_IN_CURRENT_INGREDIENTS = "DELETE_IN_CURRENT_INGREDIENTS";
export const START_SET_INGREDIENTS = "START_SET_INGREDIENTS";
