export const GET_PLACES_SUCCES = "GET_PLACES_SUCCES";
export const GET_PLACES_FAILURE = "GET_PLACES_FAILURE";
export const GET_PLACES_STARTED = "GET_PLACES_STARTED";
export const GET_ALL_PLACES_SUCCESS = "GET_ALL_PLACES_SUCCESS";
